<Project Sdk="Aspire.AppHost.Sdk/13.5.3">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <UserSecretsId>65280683-e903-4b5c-9104-d2540436d3ae</UserSecretsId>
    <NoWarn>$(NoWarn);ASPIRE010</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Heum.BackgroundService\Heum.BackgroundService.csproj" />
    <ProjectReference Include="..\Heum.Functions\Heum.Functions.csproj" />
    <ProjectReference Include="..\Heum.MigrationService\Heum.MigrationService.csproj" />
    <ProjectReference Include="..\Heum.Server\Heum.Server.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.Azure.AppConfiguration" />
    <PackageReference Include="Aspire.Hosting.Azure.Functions" />
    <PackageReference Include="Aspire.Hosting.Azure.Storage" />
    <PackageReference Include="Aspire.Hosting.Azure.ServiceBus" />
    <PackageReference Include="Aspire.Hosting.JavaScript" />
    <PackageReference Include="Aspire.Hosting.Keycloak" />
    <PackageReference Include="Aspire.Hosting.PostgreSQL" />
    <PackageReference Include="Aspire.Hosting.Redis" />
    <PackageReference Include="CommunityToolkit.Aspire.Hosting.MailPit" />
  </ItemGroup>

</Project>
