<Project Sdk="Aspire.AppHost.Sdk/13.4.6">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>65280683-e903-4b5c-9104-d2540436d3ae</UserSecretsId>
    <NoWarn>$(NoWarn);NU1903;NU1902</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Heum.Server\Heum.Server.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.JavaScript" Version="13.4.6" />
    <PackageReference Include="Aspire.Hosting.Redis" Version="13.4.6" />
  </ItemGroup>
</Project>
