<Project Sdk="Aspire.AppHost.Sdk/13.5.3">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>65280683-e903-4b5c-9104-d2540436d3ae</UserSecretsId>
    <NoWarn>$(NoWarn);NU1903;NU1902</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Heum.BackgroundService\Heum.BackgroundService.csproj" />
    <ProjectReference Include="..\Heum.Functions\Heum.Functions.csproj" />
    <ProjectReference Include="..\Heum.MigrationService\Heum.MigrationService.csproj" />
    <ProjectReference Include="..\Heum.Server\Heum.Server.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.Azure.Functions" Version="13.5.3" />
    <PackageReference Include="Aspire.Hosting.Azure.ServiceBus" Version="13.5.3" />
    <PackageReference Include="Aspire.Hosting.JavaScript" Version="13.5.3" />
    <PackageReference Include="Aspire.Hosting.Keycloak" Version="13.5.3-preview.1.26425.3" />
    <PackageReference Include="Aspire.Hosting.PostgreSQL" Version="13.5.3" />
    <PackageReference Include="Aspire.Hosting.Redis" Version="13.5.3" />
    <PackageReference Include="CommunityToolkit.Aspire.Hosting.MailPit" Version="13.5.0" />
  </ItemGroup>
</Project>
