<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <InternalsVisibleTo Include="Heum.Server.xUnit" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Azure.Messaging.ServiceBus" />
        <PackageReference Include="Microsoft.Extensions.Caching.Abstractions" />
        <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" />
        <PackageReference Include="Microsoft.Extensions.Http" />
        <PackageReference Include="Microsoft.Extensions.Options.DataAnnotations" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Heum.Contracts\Heum.Contracts.csproj" />
    </ItemGroup>

</Project>
