<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <NoWarn>$(NoWarn);NU1903;NU1902</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Heum.Server.xUnit" />
    <InternalsVisibleTo Include="Heum.Server.xIntegration" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Heum.Contracts\Heum.Contracts.csproj" />
    <ProjectReference Include="..\Heum.Data\Heum.Data.csproj" />
    <ProjectReference Include="..\Heum.Infrastructure\Heum.Infrastructure.csproj" />
    <ProjectReference Include="..\Heum.ServiceDefaults\Heum.ServiceDefaults.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Azure.Messaging.ServiceBus" Version="13.4.6" />
    <PackageReference Include="Aspire.Keycloak.Authentication" Version="13.4.6-preview.1.26319.6" />
    <PackageReference Include="Aspire.StackExchange.Redis.DistributedCaching" Version="13.4.6" />
    <PackageReference Include="Aspire.StackExchange.Redis.OutputCaching" Version="13.4.6" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.0" />
    <PackageReference Include="Scalar.AspNetCore" Version="2.16.19" />
  </ItemGroup>
</Project>
