<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <PackageReference Include="Aspire.Npgsql.EntityFrameworkCore.PostgreSQL" />
        <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Heum.Application\Heum.Application.csproj" />
        <ProjectReference Include="..\Heum.Contracts\Heum.Contracts.csproj" />
    </ItemGroup>

</Project>
